### ISSUE TITLE
pip install失败

### ISSUE THREAD

**Issue by William-liuyuxvan** [Aurorabili/fuckfif#5]
ubuntu20.04
Python 3.8.10
首先运行了sudo apt install python3-pip安装pip，后面运行pip install -r requirements.txt出现ERROR: No matching distribution found for TTS==0.17.4 (from -r requirements.txt (line 2))

**Comment by William-liuyuxvan** [comment]
请问一下怎么解决呢？

**Comment by Aurorabili** [comment]
TTS在python>=3.9<3.12进行了测试。详见[TTS 安装说明](https://github.com/coqui-ai/TTS/tree/dev#installation)。

另外，你可以尝试移除`requirements.txt`中的版本限制，我只是在0.17.4上做了测试和开发，但我相信fuckfif向更高版本兼容。

requirements.txt
```
- TTS==0.17.4
+ TTS
```

**Comment by William-liuyuxvan** [comment]
谢谢 降低版本已经解决

**Comment by Aurorabili** [comment]
关闭。若有其他问题请重新打开。
