### ISSUE TITLE
关于ffmpeg

### ISSUE THREAD

**Issue by xuecheng990531** [Aurorabili/fuckfif#7]
代码好像在执行的过程中需要用到ffmpeg，在我运行的时候会卡在ffmpeg阶段无法进行后续的操作，请问您知道原因吗
<img width="852" alt="截屏2024-12-10 15 37 24" src="https://github.com/user-attachments/assets/e5e692ba-5b38-4a56-8b0c-1348b671d8a2">

**Comment by xuecheng990531** [comment]
> 代码好像在执行的过程中需要用到ffmpeg，在我运行的时候会卡在ffmpeg阶段无法进行后续的操作，请问您知道原因吗

![Uploading 截屏2024-12-10 15.37.24.png…]()

**Comment by xuecheng990531** [comment]
> 代码好像在执行的过程中需要用到ffmpeg，在我运行的时候会卡在ffmpeg阶段无法进行后续的操作，请问您知道原因吗

<img width="852" alt="截屏2024-12-10 15 37 24" src="https://github.com/user-attachments/assets/be805aa9-513f-4609-be17-85d12cf64b63">

**Comment by Yoreh2024** [comment]
这个项目是使用的命令行调用的ffmpeg，所以与项目有关的可能性不大。
或许你可以运行一些命令测试ffmpeg是否正常？比如将音频外放？
`ffmpeg -nostats -vn -i tmp/tmep.mav -autoexit`
（这段代码直接找ai要的，如果出错了是正常的）
（我不是作者，只是路人）

**Comment by xuecheng990531** [comment]
谢谢！

**Comment by Aurorabili** [comment]
你可以直接用播放器播放`tmp/temp.wav`来检查tts是否正确合成了声音，你截图中的这个音频文件时间只有1秒多，fuckfif已知的问题是当前版本的tts在合成单个单词时效果不佳，导致在完成朗读单词相关的作业任务时会卡住。目前妥协的方案是你可以自己朗读完卡住的单词任务后继续使用脚本。我还注意到`speed=0.00173x`，这应该是不对劲的，不过这应该与fuckfif无关。
